import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './BudgetCard.css';
export default function BudgetCard({ budget, onEdit, onDelete, onCheckAlerts, }) {
    const percentage = Math.min((budget.spentAmount / budget.limitAmount) * 100, 100);
    const isExceeded = percentage >= 100;
    const isWarning = percentage >= 80 && percentage < 100;
    const isOk = percentage < 80;
    const statusClass = isExceeded ? 'exceeded' : isWarning ? 'warning' : 'ok';
    return (_jsxs("div", { className: `budget-card ${statusClass}`, children: [_jsxs("div", { className: "budget-card-header", children: [_jsxs("div", { children: [_jsx("h3", { children: budget.category.replace('_', ' ') }), _jsx("small", { className: "text-secondary", children: budget.month })] }), _jsxs("span", { className: `status-badge ${statusClass}`, children: [percentage.toFixed(0), "%"] })] }), _jsx("div", { className: "budget-card-progress", children: _jsx("div", { className: "progress-track", children: _jsx("div", { className: `progress-fill ${statusClass}`, style: { width: `${Math.min(percentage, 100)}%` } }) }) }), _jsxs("div", { className: "budget-card-stats", children: [_jsxs("div", { className: "stat", children: [_jsx("span", { className: "stat-label", children: "Spent" }), _jsxs("span", { className: "stat-value", children: ["$", budget.spentAmount.toFixed(2)] })] }), _jsxs("div", { className: "stat", children: [_jsx("span", { className: "stat-label", children: "Limit" }), _jsxs("span", { className: "stat-value", children: ["$", budget.limitAmount.toFixed(2)] })] }), _jsxs("div", { className: "stat", children: [_jsx("span", { className: "stat-label", children: "Remaining" }), _jsxs("span", { className: `stat-value ${isExceeded ? 'negative' : ''}`, children: ["$", Math.max(budget.remainingAmount, 0).toFixed(2)] })] })] }), isExceeded && (_jsxs("div", { className: "alert alert-error mt-3", children: ["Budget exceeded by $", (budget.spentAmount - budget.limitAmount).toFixed(2)] })), _jsxs("div", { className: "budget-card-actions", children: [_jsx("button", { onClick: () => onCheckAlerts(budget.id), className: "btn btn-sm btn-secondary", children: "Check Alerts" }), _jsx("button", { onClick: () => onEdit(budget), className: "btn btn-sm btn-secondary", children: "Edit" }), _jsx("button", { onClick: () => onDelete(budget.id), className: "btn btn-sm btn-danger", children: "Delete" })] })] }));
}
